#!/bin/bash

# Generated by gemini cli

set -e

README_FILE="README.md"

# Header of the README
cat >"$README_FILE" <<'EOF'
# LeetCode Solutions

This repository contains my solutions to LeetCode problems, organized by programming language.

## Structure

-   /go: Solutions written in Go.

## Table of Contents

EOF

# Generate the table of contents
TOC=""
FILES=$(find go -name "*.go" -not -name "template.go" | sort -V)
for FILE in $FILES; do
  PROBLEM_NUMBER=$(echo "$FILE" | cut -d'/' -f2)
  LINK="[Solution]($FILE)"
  TOC="$TOC| $PROBLEM_NUMBER | $LINK |\n"
done

if [ -n "$TOC" ]; then
  TOC_MARKDOWN="| Problem | Solution |\n|---|---|
$TOC"
  echo -e "$TOC_MARKDOWN" >>"$README_FILE"
else
  echo "No solutions found yet." >>"$README_FILE"
fi
